'use client'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { Modal } from '@/components/Modal'

type Ingredient = {id:string;name:string;active:boolean;unit?:{code:string}|null}
type Unit = {id:string;code:string;name:string}
type Mapping = {source_key:string;name:string;source_unit:string;ingredient_id:string|null;factor:number|null}
type Source = {source_key:string;recipe_id:string;quantity:number;recipe:{name:string}|null}
export function CarteAssociations({ingredients,units,onSaved}:{ingredients:Ingredient[];units:Unit[];onSaved:()=>Promise<void>}) {
 const [mappings,setMappings]=useState<Mapping[]>([]),[sources,setSources]=useState<Source[]>([])
 const [query,setQuery]=useState(''),[onlyPending,setOnlyPending]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 const [creating,setCreating]=useState<Mapping|null>(null),[name,setName]=useState(''),[unit,setUnit]=useState('')
 async function refresh(){const [m,s]=await Promise.all([supabase!.from('carte_mappings').select('*').order('name'),supabase!.from('carte_sources').select('source_key,recipe_id,quantity,recipe:recipes(name)')]);if(m.error)throw m.error;if(s.error)throw s.error;setMappings(m.data);setSources(s.data as unknown as Source[])}
 useEffect(()=>{let active=true;refresh().catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 async function save(m:Mapping,id:string,weight:number|null){setBusy(true);setError('');setMessage('');try{const r=await supabase!.rpc('associate_carte',{p_key:m.source_key,p_ingredient:id||null,p_weight:weight});if(r.error)throw r.error;await Promise.all([refresh(),onSaved()]);setMessage(`Associazione salvata: ${r.data} piatti aggiornati.`)}catch(e){setError(e instanceof Error?e.message:(e as {message:string}).message)}finally{setBusy(false)}}
 async function create(){if(!creating||!name.trim()||!unit)return;setBusy(true);setError('');try{const duplicate=ingredients.find(i=>i.name.trim().toLowerCase()===name.trim().toLowerCase());if(duplicate)throw new Error('Questo ingrediente esiste già: selezionalo dall’elenco.');const r=await supabase!.from('ingredients').insert({name:name.trim(),unit_id:unit,active:true}).select('id').single();if(r.error)throw r.error;await onSaved();const chosenUnit=units.find(u=>u.id===unit)!;const compatible=chosenUnit.code===creating.source_unit||(creating.source_unit==='g'&&chosenUnit.code==='kg');if(compatible){const a=await supabase!.rpc('associate_carte',{p_key:creating.source_key,p_ingredient:r.data.id,p_weight:null});if(a.error)throw new Error('Ingrediente creato. Associazione da completare: '+a.error.message);setMessage(`Ingrediente creato e associato: ${a.data} piatti aggiornati.`)}else setMessage('Ingrediente creato. Selezionalo nella riga e indica il peso per pezzo.');setCreating(null);await Promise.all([refresh(),onSaved()])}catch(e){setError(e instanceof Error?e.message:(e as {message:string}).message)}finally{setBusy(false)}}
 const pending=mappings.filter(m=>!m.ingredient_id||!ingredients.some(i=>i.id===m.ingredient_id&&i.active)).length
 const list=mappings.filter(m=>(!onlyPending||!m.ingredient_id||!ingredients.some(i=>i.id===m.ingredient_id&&i.active))&&m.name.toLowerCase().includes(query.toLowerCase()))
 return <><section className="panel tablePanel rchTablePanel"><div className="panelHead"><h3>Associazioni Menu à la carte → ORDERS</h3><input aria-label="Cerca ingrediente à la carte" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca nome"/></div><p className="rchHint">Collega gli ingredienti del menu à la carte al magazzino ORDERS. Il salvataggio aggiorna i piatti collegati. {pending} da associare · {mappings.length-pending} associati.</p><label className="cartePendingFilter"><input type="checkbox" checked={onlyPending} onChange={e=>setOnlyPending(e.target.checked)}/> Solo da associare</label>{message&&<p className="rchHint" role="status">{message}</p>}{error&&<div className="errorBox" role="alert">{error}</div>}<div className="responsiveTable"><table><thead><tr><th>Ingrediente Menu à la carte</th><th>UM</th><th>Ingrediente ORDERS</th></tr></thead><tbody>{list.map(m=><MappingRow key={m.source_key+':'+(m.ingredient_id||'')+':'+m.factor} mapping={m} ingredients={ingredients} sources={sources.filter(s=>s.source_key===m.source_key)} busy={busy} onSave={save} onCreate={()=>{setCreating(m);setName(m.name);setUnit(units.find(u=>u.code===(m.source_unit==='g'?'kg':m.source_unit))?.id||'')}}/>)}</tbody></table>{!list.length&&<p className="rchHint">Nessun ingrediente da mostrare.</p>}</div></section>{creating&&<Modal title="Crea ingrediente" onClose={()=>{if(!busy)setCreating(null)}}><form className="formGrid" onSubmit={e=>{e.preventDefault();void create()}}><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Unità<select required value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(u=><option key={u.id} value={u.id}>{u.code} — {u.name}</option>)}</select></label><p>Potrai aggiungere prezzo e fornitore nella sezione Ingredienti.</p>{error&&<div role="alert" className="errorBox">{error}</div>}<div className="formActions"><button type="submit" className="primary" disabled={busy}>{busy?'Salvataggio…':'Crea ingrediente'}</button></div></form></Modal>}</>
}
function MappingRow({mapping:m,ingredients,sources,busy,onSave,onCreate}:{mapping:Mapping;ingredients:Ingredient[];sources:Source[];busy:boolean;onSave:(m:Mapping,id:string,weight:number|null)=>Promise<void>;onCreate:()=>void}){
 const [selected,setSelected]=useState(m.ingredient_id||''),[weight,setWeight]=useState('')
 const target=ingredients.find(i=>i.id===selected),code=target?.unit?.code
 const needsWeight=(m.source_unit==='g'&&code==='pz')||(m.source_unit==='pz'&&(code==='g'||code==='kg'))
 const compatible=!selected||code===m.source_unit||(m.source_unit==='g'&&code==='kg')||(m.source_unit==='ml'&&code==='l')||needsWeight
 const options=ingredients.filter(i=>i.active&&(i.id===selected||i.unit?.code===m.source_unit||(m.source_unit==='g'&&['kg','pz'].includes(i.unit?.code||''))||(m.source_unit==='ml'&&i.unit?.code==='l')||(m.source_unit==='pz'&&['g','kg'].includes(i.unit?.code||''))))
 const names=[...new Set(sources.map(s=>s.recipe?.name).filter(Boolean))]
 return <tr><td><strong>{m.name}</strong><details><summary>{names.length} piatti collegati</summary><ul>{sources.map((s,i)=><li key={s.recipe_id+':'+i}>{s.recipe?.name}: {s.quantity} {m.source_unit}</li>)}</ul></details></td><td>{m.source_unit}</td><td><div className="rchAssociation"><select aria-label={`Associazione ${m.name}`} value={selected} disabled={busy} onChange={e=>{const id=e.target.value;setSelected(id);setWeight('');const nextCode=ingredients.find(i=>i.id===id)?.unit?.code;const weightRequired=(m.source_unit==='g'&&nextCode==='pz')||(m.source_unit==='pz'&&(nextCode==='g'||nextCode==='kg'));if(!weightRequired)void onSave(m,id,null)}}><option value="">Da associare</option>{options.map(i=><option key={i.id} value={i.id}>{i.name} ({i.unit?.code||'—'})</option>)}</select>{needsWeight&&<><label>Peso di 1 pezzo (g)<input type="number" min="0.000001" step="any" value={weight} onChange={e=>setWeight(e.target.value)} placeholder="Es. 50"/></label><button className="primary" disabled={busy||!compatible||!(Number(weight)>0)} onClick={()=>void onSave(m,selected,Number(weight))}>Salva associazione</button></>}{!m.ingredient_id&&<button className="secondary" disabled={busy} onClick={onCreate}>Crea ingrediente</button>}</div>{!compatible&&<p role="alert">Le unità selezionate non sono compatibili.</p>}</td></tr>
}
