from pathlib import Path

p = Path('app/page.tsx')
s = p.read_text()

def rep(old, new):
    global s
    if old not in s:
        raise SystemExit(f'Pattern not found: {old[:100]}')
    s = s.replace(old, new, 1)

rep("type Client = { id: string; customer_type:", "type Client = { id: string; client_number?: number | null; customer_type:")
rep("type Ingredient = { id: string; name:", "type Ingredient = { id: string; ingredient_number?: number | null; name:")
rep("type Recipe = { id: string; name:", "type Recipe = { id: string; recipe_number?: number | null; name:")
rep("  const [editingEvent, setEditingEvent] = useState<EventRow | null>(null)\n", "  const [editingEvent, setEditingEvent] = useState<EventRow | null>(null)\n  const [editingClient, setEditingClient] = useState<Client | null>(null)\n")
rep("supabase.from('ingredients').select('id,name,category", "supabase.from('ingredients').select('id,ingredient_number,name,category")
rep("supabase.from('recipes').select('id,name,category", "supabase.from('recipes').select('id,recipe_number,name,category")
rep("ingredient:ingredients(id,name,category", "ingredient:ingredients(id,ingredient_number,name,category")
rep("{section==='clients' && <Clients clients={clients} query={query} setQuery={setQuery} onNew={()=>setModal('client')}/>} ", "{section==='clients' && <Clients clients={clients} query={query} setQuery={setQuery} onNew={()=>{setEditingClient(null);setModal('client')}} onOpen={(c:Client)=>{setEditingClient(c);setModal('client')}}/>} ")
rep("{modal==='client' && <ClientModal onClose={()=>setModal(null)} onSaved={refreshAll}/>} ", "{modal==='client' && <ClientModal client={editingClient} onClose={()=>{setModal(null);setEditingClient(null)}} onSaved={refreshAll}/>} ")
old_clients = "function Clients({clients,query,setQuery,onNew}:any){const q=query.toLowerCase();const list=clients.filter((c:Client)=>[nameOfClient(c),c.phone,c.email,c.city].join(' ').toLowerCase().includes(q));return <><SearchBar value={query} setValue={setQuery} placeholder=\"Cerca cliente…\" action={<button className=\"secondary\" onClick={onNew}><Plus size={17}/> Nuovo cliente</button>}/><div className=\"cards\">{list.map((c:Client)=><article className=\"clientCard\" key={c.id}><div className=\"avatar\"><ContactRound/></div><div><span className=\"eyebrow\">{c.customer_type}</span><h3>{nameOfClient(c)}</h3><p>{c.phone||'Nessun telefono'}</p><p>{c.email||'Nessuna email'}</p>{c.city&&<small>{c.city}</small>}</div></article>)}</div>{list.length===0&&<Empty text=\"Nessun cliente trovato.\"/>}</>}"
new_clients = "function Clients({clients,query,setQuery,onNew,onOpen}:any){const q=query.toLowerCase();const list=clients.filter((c:Client)=>[c.client_number,nameOfClient(c),c.phone,c.email,c.city].join(' ').toLowerCase().includes(q));return <><SearchBar value={query} setValue={setQuery} placeholder=\"Cerca cliente o ID…\" action={<button className=\"secondary\" onClick={onNew}><Plus size={17}/> Nuovo cliente</button>}/><div className=\"cards\">{list.map((c:Client)=><article className=\"clientCard\" key={c.id} onClick={()=>onOpen(c)} role=\"button\" tabIndex={0}><div className=\"avatar\"><ContactRound/></div><div><span className=\"eyebrow\">{c.client_number?`CLIENTE #${c.client_number}`:c.customer_type}</span><h3>{nameOfClient(c)}</h3><p>{c.phone||'Nessun telefono'}</p><p>{c.email||'Nessuna email'}</p>{c.city&&<small>{c.city}</small>}</div><Pencil size={16}/></article>)}</div>{list.length===0&&<Empty text=\"Nessun cliente trovato.\"/>}</>}"
rep(old_clients, new_clients)
rep("<th>Ingrediente</th><th>Categoria</th>", "<th>ID</th><th>Ingrediente</th><th>Categoria</th>")
rep("{ingredients.map((i:Ingredient)=><tr key={i.id} onClick={()=>onOpen(i)}><td><strong>{i.name}</strong></td>", "{ingredients.map((i:Ingredient)=><tr key={i.id} onClick={()=>onOpen(i)}><td>{i.ingredient_number?`#${i.ingredient_number}`:'—'}</td><td><strong>{i.name}</strong></td>")
rep("<span className=\"eyebrow\">{categoryLabel}</span><h3>{r.name}</h3>", "<span className=\"eyebrow\">{r.recipe_number?`RICETTA #${r.recipe_number} · `:''}{categoryLabel}</span><h3>{r.name}</h3>")
old_modal = "function ClientModal({onClose,onSaved}:any){const [f,setF]=useState({customer_type:'privato',first_name:'',last_name:'',company_name:'',phone:'',email:'',city:'',notes:''});async function save(e:FormEvent){e.preventDefault();const {error}=await supabase!.from('clients').insert(f);if(error)return alert(error.message);await onSaved();onClose()}return <Modal title=\"Nuovo cliente\" onClose={onClose}><form onSubmit={save} className=\"formGrid\">"
new_modal = "function ClientModal({client,onClose,onSaved}:{client:Client|null;onClose:()=>void;onSaved:()=>Promise<void>}){const [f,setF]=useState({customer_type:client?.customer_type||'privato',first_name:client?.first_name||'',last_name:client?.last_name||'',company_name:client?.company_name||'',phone:client?.phone||'',email:client?.email||'',city:client?.city||'',notes:client?.notes||''});const [saving,setSaving]=useState(false);async function save(e:FormEvent){e.preventDefault();if(!supabase)return;setSaving(true);const res=client?await supabase.from('clients').update(f).eq('id',client.id):await supabase.from('clients').insert(f);setSaving(false);if(res.error)return alert(res.error.message);await onSaved();onClose()}async function remove(){if(!client||!supabase)return;const linked=await supabase.from('events').select('id',{count:'exact',head:true}).eq('client_id',client.id);if(linked.error)return alert(linked.error.message);if((linked.count||0)>0)return alert(`Il cliente è collegato a ${linked.count} banchetto/i e non può essere cancellato per non perdere lo storico.`);if(!confirm(`Cancellare definitivamente ${nameOfClient(client)}?`))return;const {error}=await supabase.from('clients').delete().eq('id',client.id);if(error)return alert(error.message);await onSaved();onClose()}return <Modal title={client?`Cliente #${client.client_number||'—'} · ${nameOfClient(client)}`:'Nuovo cliente'} onClose={onClose}><form onSubmit={save} className=\"formGrid\">"
rep(old_modal, new_modal)
rep("<div className=\"formActions span2\"><button type=\"button\" className=\"ghost\" onClick={onClose}>Annulla</button><button className=\"primary\">Salva cliente</button></div></form></Modal>}", "<div className=\"formActions span2\">{client&&<button type=\"button\" className=\"ghost\" onClick={remove}><Trash2 size={16}/> Elimina</button>}<button type=\"button\" className=\"ghost\" onClick={onClose}>Annulla</button><button className=\"primary\" disabled={saving}>{saving?'Salvataggio…':client?'Salva modifiche':'Salva cliente'}</button></div></form></Modal>}")

p.write_text(s)
