-- Orders NG: ID numerici progressivi visibili, mantenendo gli UUID come chiavi interne.
-- Le colonne identity assegnano automaticamente un numero ai record esistenti e futuri.

alter table public.clients
  add column if not exists client_number bigint generated by default as identity;

alter table public.ingredients
  add column if not exists ingredient_number bigint generated by default as identity;

alter table public.recipes
  add column if not exists recipe_number bigint generated by default as identity;

-- events possiede già event_number nell'attuale Orders NG: lo conserviamo come ID numerico del banchetto/evento.

create unique index if not exists clients_client_number_uidx
  on public.clients (client_number);
create unique index if not exists ingredients_ingredient_number_uidx
  on public.ingredients (ingredient_number);
create unique index if not exists recipes_recipe_number_uidx
  on public.recipes (recipe_number);

comment on column public.clients.client_number is 'ID numerico progressivo visibile del cliente';
comment on column public.ingredients.ingredient_number is 'ID numerico progressivo visibile dell ingrediente';
comment on column public.recipes.recipe_number is 'ID numerico progressivo visibile della ricetta';
comment on column public.events.event_number is 'ID numerico progressivo visibile del banchetto/evento';
