create table public.rch_mappings (
 rch_id bigint primary key check(rch_id>0), name text not null,
 unit_code integer not null check(unit_code in (1,3,4)),
 ingredient_id uuid references public.ingredients(id) on delete set null,
 excluded boolean not null default false
);
create index rch_mappings_ingredient_idx on public.rch_mappings(ingredient_id);
create table public.rch_imports (
 id uuid primary key default gen_random_uuid(),filename text not null,
 period_from date not null,period_to date not null check(period_to>=period_from),
 file_hash text not null unique,rows jsonb not null check(jsonb_typeof(rows)='array'),
 mappings jsonb not null check(jsonb_typeof(mappings)='array'),
 created_at timestamptz not null default now(),
 exclude using gist (daterange(period_from,period_to,'[]') with &&)
);
alter table public.rch_mappings enable row level security;
alter table public.rch_imports enable row level security;
revoke all on public.rch_mappings,public.rch_imports from anon,authenticated;
grant select,insert,update,delete on public.rch_mappings,public.rch_imports to authenticated;
create policy "management RCH mappings" on public.rch_mappings for all to authenticated
 using ((select auth.uid()) is not null and coalesce(auth.jwt()->>'email','')<>'' and auth.jwt()->>'email'<>'cucina@officinaventidue.it')
 with check ((select auth.uid()) is not null and coalesce(auth.jwt()->>'email','')<>'' and auth.jwt()->>'email'<>'cucina@officinaventidue.it');
create policy "management RCH imports" on public.rch_imports for all to authenticated
 using ((select auth.uid()) is not null and coalesce(auth.jwt()->>'email','')<>'' and auth.jwt()->>'email'<>'cucina@officinaventidue.it')
 with check ((select auth.uid()) is not null and coalesce(auth.jwt()->>'email','')<>'' and auth.jwt()->>'email'<>'cucina@officinaventidue.it');

insert into public.rch_mappings(rch_id,name,unit_code,excluded) values
(231,'Pinsa',4,false),
(234,'Noci',1,false),
(239,'Cannolo SuperMignon',4,false),
(242,'Gelatina Carte d''Or',1,false),
(244,'Miele',1,false),
(246,'Passata pomodoro',1,false),
(247,'Peperoni',1,false),
(248,'Mandorle',1,false),
(249,'Mango',1,false),
(250,'Mascarpone',1,false),
(251,'Melograno',1,false),
(252,'Miyazaki Japanese',1,false),
(253,'Mortadella',1,false),
(254,'Nocciole',1,false),
(255,'Noce di Manzo',1,false),
(256,'Noce di manzo GELO',1,false),
(258,'Pan di stelle',1,false),
(259,'Passata di datterino giallo',1,false),
(260,'Pasta di salsiccia',1,false),
(261,'Patate fritte',1,false),
(262,'Pesche sciroppate',1,false),
(263,'Petto di pollo',1,false),
(264,'Pomodorini secchi',1,false),
(265,'Porri',1,false),
(267,'Reale di Wagyu',1,false),
(268,'Rucola',1,false),
(269,'Sciroppo frutto della passione',1,false),
(270,'Semi di Papavero',1,false),
(271,'Senape',1,false),
(272,'Spinacino',1,false),
(273,'Stracchino',1,false),
(274,'Sushi Rice',1,false),
(276,'Timo',1,false),
(277,'Topping aceto balsamico',1,false),
(279,'Torroncino Carte D''Or',1,false),
(280,'Catalana Carte d''Or',1,false),
(281,'Tuorlo uova',1,false),
(282,'Uova',4,false),
(283,'Albume uova',1,false),
(284,'Yogurt',1,false),
(285,'Zucca',1,false),
(286,'Grand Marnier',3,false),
(287,'Alga nori',4,false),
(288,'Lime',1,false),
(289,'Limoni',1,false),
(290,'Mini Tomini',4,false),
(291,'Ravioli di ricotta',4,false),
(292,'Burro',1,false),
(293,'Avocado',1,false),
(294,'Composta di Cipolla',1,false),
(295,'Cipolla croccante',1,false),
(296,'Grana a scaglie',1,false),
(297,'Granella di pistacchi',1,false),
(298,'Confettura di fichi',1,false),
(299,'Basilico',1,false),
(300,'Panna di soia',1,false),
(302,'Stracciatella',1,false),
(303,'Insalata mista',1,false),
(304,'Insalata premium',1,false),
(305,'Songino',1,false),
(306,'Macinato bovino e suino',1,false),
(307,'Filetto suino',1,false),
(308,'Filetto bovino',1,false),
(309,'Fettuccine ai mirtilli',1,false),
(310,'Cantucci',1,false),
(311,'Cavolo cappuccio rosso',1,false),
(312,'Gnocchi viola',1,false),
(313,'Gnocchi gialli',1,false),
(314,'Gorgonzola',1,false),
(315,'Bufaline',1,false),
(316,'Bubble tea',1,false),
(317,'Taleggio',1,false),
(319,'Castagne',1,false),
(320,'Nutella',1,false),
(321,'Piselli gelo',1,false),
(322,'Salsa Tartara',1,false),
(323,'Purè di patate',1,false),
(324,'Funghi Nameko',1,false),
(325,'Pecorino grattugiato',1,false),
(326,'Pecorino stagionato',1,false),
(327,'Ricotta di pecora',1,false),
(328,'Lardo',1,false),
(329,'Topping per dessert',1,false),
(330,'Radicchio',1,false),
(331,'Frutti di bosco',1,false),
(333,'Erba cipollina',1,false),
(334,'Dessert no glutine',4,false),
(335,'Datterino rosso fresco',1,false),
(336,'Guanciale al brandy',1,false),
(337,'Reale bovino',1,false),
(338,'Agnolotti',1,false),
(339,'Amaretti',1,false),
(340,'Arancia',1,false),
(341,'Capperi',1,false),
(342,'Ricotta mista',1,false),
(344,'Carpaccio affumicato',1,false),
(345,'Formaggio grattuggiato',1,false),
(346,'Ceci',1,false),
(348,'Cioccolato fondente',1,false),
(349,'Cetrioli',1,false),
(350,'Ferfellone',1,false),
(351,'Fusilloni all''uovo',1,false),
(352,'Friarielli',1,false),
(353,'Julienne di verdure',1,false),
(354,'Latte',1,false),
(355,'Prosciutto crudo',1,false),
(356,'Vini bianchi',4,true),
(357,'Vini rossi',4,true),
(358,'Vini spumantizzati',4,true),
(359,'Panna da cucina',1,false),
(360,'Panna 38%',1,false),
(361,'Tartufo in carpaccio',1,false),
(362,'Succo di  lime',1,false),
(363,'Misto uova pastorizzate',1,false),
(364,'Polenta',1,false),
(365,'Maionese di soia',1,false),
(366,'Polpa di mandarino',1,false),
(367,'Carrè agnello',1,false),
(368,'Chitarra',1,false),
(369,'Zucchero',1,false),
(370,'Zucchine',1,false),
(371,'Melanzane',1,false),
(372,'Nuggets',1,false),
(374,'Vini rosati',4,true),
(380,'Rapa rossa',1,false),
(381,'Hugo liquore',1,false),
(382,'Philadelphia',1,false),
(383,'Fragole',1,false),
(385,'Pappardelle',1,false),
(386,'Tonnarelli',1,false),
(387,'Pancetta',1,false),
(388,'Pasta briseé',4,false),
(389,'Funghi Champignon',1,false),
(390,'Patate',1,false),
(391,'Ananas',1,false),
(392,'Farina 00',1,false),
(393,'Passata di datterino rosso',1,false);
update public.rch_mappings m set ingredient_id=s.id from (
 select m.rch_id, (array_agg(i.id))[1] as id
 from public.rch_mappings m join public.ingredients i on lower(trim(i.name))=lower(trim(m.name))
 join public.units u on u.id=i.unit_id
 where i.active and not m.excluded and ((m.unit_code=1 and u.code in ('g','kg')) or (m.unit_code=3 and u.code in ('ml','l')) or (m.unit_code=4 and u.code='pz'))
 group by m.rch_id having count(*)=1
) s where m.rch_id=s.rch_id;
